id = "qubik-theme"
name = "Qubik"
version = "0.1.0"
schema_version = 1
authors = ["qnbhd <1qnbhd@gmail.com>"]
description = "Qubik theme for Zed"
repository = "https://github.com/qnbhd/qubik-theme-zed"
